### ISSUE TITLE
Add Account Switcher Mod

### ISSUE THREAD

**Issue by V3XX** [HyperiumClient/Hyperium#632]
**Is your feature request related to a problem? If so, please describe.**   
  
Nope, it's not related to a problem.
**Describe the solution you'd like**
  
I think adding account switcher mod would be a great addition to Hyperium's features, considering Badlion Client already has it. Even though I prefer hyperium over badlion, I still have to use badlion because it's a huge hassle to get out and back into MC every time  I need to switch accounts.
**Describe alternatives you've considered**  
  

**Additional context**

**Comment by RDIL** [comment]
Planned.

**Comment by asbyth** [comment]
as rdil said, it's been planned for months, just nobodies cared to pick it up and finish it, but ours is going to function differently, which will allow you to choose from ingame, but will still restart the game, because of security reasons + it's just better to restart to avoid other issues that can come up

**Comment by asbyth** [comment]
> oh! cool! any idea when it's coming?

like i said, nobodies cared to pick it up and finish it, so absolutely zero date for anything

**Comment by asbyth** [comment]
soon:tm:
